### ISSUE TITLE
Default cardinalities should be shown

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/model-driven-data#114]
I propose to show all cardinalities, including the default ones. Currently 0..* is the default cardinality. It is not shown:

<img width="718" alt="image" src="https://user-images.githubusercontent.com/4235208/149832776-cc3c6f64-b406-4983-b60b-dfb1b6773e1c.png">

While it seems as a useful simplification of the UI, it may cause UX problems. We cannot be sure how a reader interprets a property without a cardinality. Do they interpret it as missing / not specified / 1..1 / 0..*?

As the best solution to this UX problem, I propose to show all cardinalities.

**Comment by jakubklimek** [comment]
I agree.
