### ISSUE TITLE
Link from schema generator to specification manager

### ISSUE THREAD

**Issue by martinnec** [opendata-mvcr/model-driven-data#116]
In schema generator, I would like to have a link back to the specification manager to the detail of the specification of the opened PSM schema. Currently, I use "back" in the browser.

**Comment by martinnec** [comment]
Sometimes, "back" button from the schema generator does not work:

![image](https://user-images.githubusercontent.com/4235208/150197928-abf249fe-f49a-4bbf-a067-42bfb13523a7.png)

**Comment by sstenchlak** [comment]
Fixed by redirects file in Netlify configuration.
