### ISSUE TITLE
PSM operations

### ISSUE THREAD

**Issue by sstenchlak** [opendata-mvcr/model-driven-data#14]
Following PSM operations are required for now.

**Schema**
- [x] Create schema
- [x] Modify schema label and description
- [x] Set schema root _(only at creation)_

**Class**
- [x] Create (interpreted) class
- [x] Modify class label and description
- [x] Modify class technical label
- [x] Change order of class parts

**Attribute**
- [x] Create (interpreted) attribute
- [x] Modify attribute label and description
- [x] Modify attribute technical label
- [x] Delete attribute (+delete itself from class parts)

**Association**
- [x] Create (interpreted) association
- [x] Modify association label and description
- [x] Modify association technical label
- [x] Delete association (+delete itself from class parts)

**Comment by skodapetr** [comment]
@sstenchlak What is the meaning of "interpreted" ? Just that you can set an interpretation?

**Comment by sstenchlak** [comment]
@skodapetr Sorry for the confusion. Yes. In this case, you can set an interpretation, but it is needed only during the create operation, when the class has no members, so we do not have to implement complex precondition rules.

**Comment by skodapetr** [comment]
It should be all available. About the interpretation, as of now we do not address this issue. So the process is two step, first create class and next set interpretation.  The actions should try to be valid only in scope of a diagram, si there would be no way how to validate change or interpretation anyway. This cross schema validation should be implemented using validators. 

Also as of now not all things that should be validated are validated. Yet that should not impact the interface and will be solved as a part of another issue.
