### ISSUE TITLE
XML Schemas contain unnecessary xs:choice

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/model-driven-data#144]
Even with a simple model like this one:
![image](https://user-images.githubusercontent.com/718827/155134950-fbd0f4d7-5d2c-4839-9c3e-292b89c215ca.png)

the resulting XSD (annotations removed) contains unnecessary `xs:group` and unnecessary `xs:choice`:
```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1" elementFormDefault="unqualified">
  <xs:group name="ridicak">
    <xs:sequence>
      <xs:element name="má_evidovaného_držitele">
        <xs:complexType>
          <xs:choice>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="agendový_identifikátor_fyzické_osoby" type="xs:anySimpleType">
              </xs:element>
            </xs:sequence>
          </xs:choice>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
  <xs:element name="ridicak">
    <xs:complexType>
      <xs:group ref="ridicak"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

Even though this might be correct, it is unnecessary and makes the schema a harder to read. 
The expected form would be (using the [Russian doll design pattern](https://www.oracle.com/technical-resources/articles/java/design-patterns.html#:~:text=Is%20difficult%20to%20read%20and%20understand.-,Russian%20Doll,You%20must%20define%20only%20the%20root%20element%20within%20the%20global%20namespace.)):
```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1">
  <xs:element name="ridicak">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="má_evidovaného_držitele">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" name="agendový_identifikátor_fyzické_osoby" type="xs:anySimpleType"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
```
[artifact.zip](https://github.com/opendata-mvcr/model-driven-data/files/8116759/artifact.zip)

**Comment by cermakmarek** [comment]
It has become this complex due to a possible reuse in a specification, where having a group is necessary. This behaviour could be disabled, but then there has to be some sort of indication whether the schema is potentially reused or not.

With inheritance in mind, a fully reusable schema might even look like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1">
  <xs:group name="ridicak">
    <xs:sequence><!-- ... --></xs:sequence>
  </xs:group>
  <xs:complexType name="ridicak">
    <xs:group ref="ridicak"/>
  </xs:complexType>
  <xs:element name="ridicak" type="ridicak"/>
</xs:schema>
```

I am not sure if there is a better way, i.e. to only provide an element declaration and have some or of "implicit" type or group of such an element to use in other places.

**Comment by jakubklimek** [comment]
I am not sure what kind of reuse you mean here, could you give an example?
Is it reuse of this schema as a whole in another schema, i.e. via `xs:import` as in [this XSD for people and companies](https://ofn.gov.cz/lidé-a-osoby/2020-07-01/schémata/člověk-či-osoba.xsd)?

**Comment by cermakmarek** [comment]
Yes, via `xs:import` or `xs:include`. In that case, the element `ridicak` may be a target of a non-materialized property and the easiest way to include it there is via the group.

**Comment by jakubklimek** [comment]
I see. The questions is, whether we should presume this, or even support this case, since it makes the schema less readable. But OK, lets move this into another issue, and keep the unnecessary `xs:choice` here.

**Comment by cermakmarek** [comment]
I realize I have also missed the part about `<xs:choice>` – yes that is superfluous and will be eventually fixed (it's there really just in case of multiple property types).
