### ISSUE TITLE
PIM operations

### ISSUE THREAD

**Issue by sstenchlak** [opendata-mvcr/model-driven-data#15]
Following PIM operations are required for now.

**Schema**
- [x] Create schema
- [ ] Modify schema label and description

**Class**
- [x] Create class
- [ ] Modify class label and description
- [x] Delete class

**Attribute**
- [x] Create attribute
- [ ] Modify attribute label and description
- [ ] Modify attribute datatype
- [x] Delete attribute

**Association**
- [x] Create association
- [ ] Modify association label and description
- [x] Delete association

**Comment by skodapetr** [comment]
The human label/description and technical label are implemented for all resources using a single action.
