### ISSUE TITLE
There is one extra dot in CSV schema file name

### ISSUE THREAD

**Issue by JanJanda** [opendata-mvcr/model-driven-data#155]
When I download CSV schema artefact, the file name has an extra dot. Example: `Jazyk..csv-metadata.json`

**Comment by sstenchlak** [comment]
Can you please provide more detail on how to reproduce the error?

For example, https://kodi-specification-manager.netlify.app/specification/2ba9a878-2ec8-45f5-b37d-f571d65751ed generates the CSV correctly.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/23003372/157646343-b209f793-5b4a-4067-a82c-0366457aed6a.png">

**Comment by JanJanda** [comment]
This way.
![image](https://user-images.githubusercontent.com/68281650/157658001-9b94b946-db71-49fb-8721-2af68d105ed6.png)
