### ISSUE TITLE
PSM attributes do not get the "Význam" annotation with CIM IRI

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/model-driven-data#156]
See [here](https://deploy-preview-154--kodi-schema-generator.netlify.app/?configuration=https%3A%2F%2Fspecification-manager-backend.mercadia.cz%2Fconfiguration%2Fby-data-psm%2Fe148a984-ac60-4141-bca3-0f5933a7a0bf&backlink=https%3A%2F%2Fdeploy-preview-154--kodi-specification-manager.netlify.app%2Fspecification%2F10b4b4d6-7145-4d10-83cf-2fc0f92b7c2e) 
The XML element representing `agendový_identifikátor_fyzikcé_ososby` is missing the CIM IRI `https://slovník.gov.cz/legislativní/sbírka/111/2009/pojem/agendový-identifikátor-fyzické-osoby` in the annotation:
![image](https://user-images.githubusercontent.com/718827/157652597-b0c11370-152e-4040-abe0-5ef9985fdacd.png)

**Comment by cermakmarek** [comment]
All annotations get their data from the associated `StructureModelClass` or `StructureModelProperty`, if present, so `cimIri` is probably missing on the `StructureModelProperty` instance. @sstenchlak is this possible?

**Comment by sstenchlak** [comment]
Yes, you are right. It should be fixed in main.
I have forgotten to change the branch; please close this issue if resolved.
