### ISSUE TITLE
Czech characters in technical label

### ISSUE THREAD

**Issue by JanJanda** [opendata-mvcr/model-driven-data#160]
Technical labels in structure model contain czech characters (ěščřžýáíéúů). I want to ask whether it wouldn't be better to use ASCII only.
![image](https://user-images.githubusercontent.com/68281650/157887294-8a46c76a-260c-42d3-a8e3-c1c7a2d6b763.png)

**Comment by jakubklimek** [comment]
It is not better. We do not support "cestina bez hacku a carek" - it is an unnecessary transformation since every reasonable data format supports UTF-8 anyway.

**Comment by cermakmarek** [comment]
In the case of viewing CSV, including the UTF-8 BOM (0xEF 0xBB 0xBF) might fix issues when displaying such data in Excel.

**Comment by jakubklimek** [comment]
Usage of BOM is discouraged, as UTF-8 (without BOM) is the standard encoding.

The goal of proper CSV representation is not its easy opening in Excel, which is known for bad CSV support.

Also see https://opendata.gov.cz/špatná-praxe:start#nejčastější_chyby_při_použití_formátu_csv
