### ISSUE TITLE
Indicate lowering and lifting function in generated XSLT's file name

### ISSUE THREAD

**Issue by jakubklimek** [opendata-mvcr/model-driven-data#171]
Currently, both the lifting and lowering XSLT file names are identical and match the PSM name. They should be differentiated by function, e.g.
``Řidičský průkaz České republiky - lowering.xslt`` and ``Řidičský průkaz České republiky - lifting.xslt``

**Comment by cermakmarek** [comment]
Fixed by d93cc32b170a40b2daa4fc6578c77aa59061c763. It is now `.lowering.xslt` and `.lifting.xslt`, since only the extension can be changed.
