### ISSUE TITLE
cimIri is not propagated in reused specifications

### ISSUE THREAD

**Issue by cermakmarek** [opendata-mvcr/model-driven-data#174]
When a specification is reused, its PSM is included in the `StructureModel`, but `cimIri` is not set on the included classes and properties. Normally this wouldn't be an issue, as most of the generators can import the proper artifact for the reused specification, but there is an issue with SPARQL as it doesn't offer any composition of queries. It needs to be able to access the interpretations of all classes and properties, whether used directly or indirectly.

If this is intended, what would be the correct way to obtain the interpretations, assuming generators should only work with the `StructureModel` they are provided with?

**Comment by sstenchlak** [comment]
The correct way would be to transform the structure model with all the conceptual models that are reused, or reused recursivelly by the current conceptual model. (or simply with all of them) The structure model already contains the whole tree with reuses, but things such as cimIri need to be added by transformations.

```ts
for (const conceptualModel of Object.values(context.conceptualModels) {
  model = transformStructureModel(
    conceptualModel,
    model,
    Object.values(context.specifications)
  );
}
```

https://github.com/opendata-mvcr/model-driven-data/blob/e88941dff2d58f3ae46e6005c8971e95f32383e6/packages/core/src/xml-schema/xml-schema-generator.ts#L53-L57
