### ISSUE TITLE
HttpFetch proxy to throttle communication

### ISSUE THREAD

**Issue by sstenchlak** [opendata-mvcr/model-driven-data#25]
Implement a proxy for httpFetch to limit the number of concurrent requests.

**Comment by skodapetr** [comment]
Just to clarify, the purpose is to limit the number of request made to a single server in short period of time. This is needed as some operations may result in hundreds of SPARQL queries - we do not want to ask so many queries at once.

**Comment by sstenchlak** [comment]
This feature is not relevant to the current state of the project. The intention was to limit the number of requests for stores that need to fetch each resource separately. We are using stores that download everything in advance in a single request.

This issue might be reopened in the future when it becomes relevant again.
